name: run main.py

concurrency: 1

on:
    push:
      branches: ['main']

jobs:

  deploy:
    name: 'Deploy bundle'
    runs-on: ubuntu-latest

    steps:
      # Check out this repo, so that this workflow can access it.

      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "Build wheel file"
        run: uv build --wheel

      - name: "Build app.yml file"
        run: >
            cat > app.yml<<EOF
            command: ['streamlit', 'run', 'app.py']
            env:
            - name: 'OPENAI_API_KEY'
                value: ${{ secrets.OPENAI_API_KEY }}
            EOF
